//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaWebRazor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVentas
    {
        public int IdDetalleVenta { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> IdVentas { get; set; }
        public Nullable<int> IdProducto { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Ventas Ventas { get; set; }
    }
}
